title: APPEX Training Guide
description: An Interdisciplinary Approach to Pandemic Science
url: "https://wrgr.github.io"
baseurl: "/appex-training"

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - foundation/index.md
  - archetypes/index.md
  - advanced/index.md
  - references/index.md
  - external-link.md

# Collections
collections:
  archetypes:
    output: true
    permalink: /:collection/:name/
  notebooks:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "archetypes"
      type: "pages"
    values:
      layout: "archetypes"
  - scope:
      path: "notebooks"
      type: "pages"
    values:
      layout: "notebook"

# Custom variables
appex:
  version: "1.0"
  authors: "APPEX Research Team"
